[package]
name = "jsonrpsee"
description = "JSON-RPC crate"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
edition = "2018"

[workspace]
members = [
    "core",
    "http",
]

[dependencies]
jsonrpsee-core = { path = "core" }
jsonrpsee-http = { path = "http", optional = true }

[features]
default = ["http"]
http = ["jsonrpsee-http"]
