name: Rust

on: [push]

jobs:
  build:
    runs-on: parity/rust:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
